### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by wge44** [dborth/libwiigui#27]
I'm trying to compile the code but I'm getting this error:

oggplayer.c
C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/oggplayer.c:32:10: fatal error: tremor/ivorbiscodec.h: No such file or directory
   32 | #include <tremor/ivorbiscodec.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:18: oggplayer.o] Error 1
make: *** [Makefile:101: build] Error 2

**Comment by wge44** [comment]
installing the other ppc packages with `pacman -S $(pacman -Ssq ppc)` solves the problem above

**Comment by wge44** [comment]
Currently can't get past this error

c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:242: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function `_ZL16MenuSettingsFilev':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:630: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:630: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function `_Z12WindowPromptPKcS0_S0_S0_':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:79: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o:C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:79: more undefined references to `button_over_pcm_size' follow
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function `_Z8MainMenui':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:779: undefined reference to `bg_music_ogg_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/menu.cpp:779: undefined reference to `bg_music_ogg_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_filebrowser.o: in function `_ZN14GuiFileBrowserC2Eii':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:35: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:35: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:36: undefined reference to `button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:36: undefined reference to `button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_keyboard.o: in function `_ZN11GuiKeyboardC2EPcj':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:116: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:116: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:117: undefined reference to `button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:117: undefined reference to `button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_optionbrowser.o: in function `_ZN16GuiOptionBrowserC2EiiP11_optionlist':
C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:32: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:32: undefined reference to `button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:33: undefined reference to `button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/Cameron/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:33: undefined reference to `button_click_pcm_size'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:30: /home/Cameron/Downloads/libwiigui/libwiigui-master/libwiigui-demo.elf] Error 1
make: *** [Makefile:101: build] Error 2

**Comment by wge44** [comment]
Currently can't get past this error, fails building at the end

c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:242: undefined reference to button_over_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function _ZL16MenuSettingsFilev':
C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:630: undefined reference to button_over_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:630: undefined reference to button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function _Z12WindowPromptPKcS0_S0_S0_': C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:79: undefined reference to button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o:C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:79: more undefined references to button_over_pcm_size' follow c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: menu.o: in function _Z8MainMenui':
C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:779: undefined reference to bg_music_ogg_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/menu.cpp:779: undefined reference to bg_music_ogg_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_filebrowser.o: in function _ZN14GuiFileBrowserC2Eii': C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:35: undefined reference to button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:35: undefined reference to button_over_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:36: undefined reference to button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_filebrowser.cpp:36: undefined reference to button_click_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_keyboard.o: in function _ZN11GuiKeyboardC2EPcj':
C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:116: undefined reference to button_over_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:116: undefined reference to button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:117: undefined reference to button_click_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_keyboard.cpp:117: undefined reference to button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: gui_optionbrowser.o: in function _ZN16GuiOptionBrowserC2EiiP11_optionlist': C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:32: undefined reference to button_over_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:32: undefined reference to button_over_pcm_size' c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:33: undefined reference to button_click_pcm_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/Users/WG/Downloads/libwiigui/libwiigui-master/source/libwiigui/gui_optionbrowser.cpp:33: undefined reference to `button_click_pcm_size'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:30: /home/WG/Downloads/libwiigui/libwiigui-master/libwiigui-demo.elf] Error 1
make: *** [Makefile:101: build] Error 2

**Comment by dborth** [comment]
Fixed.

**Comment by wge44** [comment]
How is it fixed? Is there a new commit coming/ is there something on my end I need to change?

**Comment by spotlightishere** [comment]
It seems at some point devkitPro's configuration for that started including the file's size in header instead of within the object, breaking the reliance of `extern const` as used within `source/filelist.h`. I was able to circumvent this by editing it to import every `bin2o`-operated file manually and rearranging `OFILES` within the Makefile to operate on CPPFILES/CFILES last so that headers/objs would be generated.

Is there a fix for this that hasn't been pushed yet? Happy to make a PR if not!

**Comment by wge44** [comment]
@spotlightishere there’s no fix currently pushed, if you can make a PR that would be great
